### ISSUE TITLE
can't find the package named topology

### ISSUE THREAD

**Issue by jiaweiwangwang** [acsicuib/GA4FogPlacement#1]
Hello,
  When I followed the steps you gave to execute the code, I found that the package named  topology SYSTEMMODEL.py was not found. Where did you find this package? I need your guidance, thanks！

**Comment by GokselKUCUKSAHIN** [comment]
**No module named topology**
![image](https://user-images.githubusercontent.com/33639948/75670848-926dc400-5c8e-11ea-91b3-8948f8c9e445.png)

**Comment by wisaaco** [comment]
The topology class is defined in another related project: https://github.com/acsicuib/YAFS/blob/master/src/yafs/topology.py

**Comment by BalasemIsawi** [comment]
No class named Entity in topology
