### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by jiaweiwangwang** [acsicuib/GA4FogPlacement#3]
Hello, I added some extensions based on your experiment, but I found that there are always problems when adjusting the json file during runtime. I want to refer to the json file generated by your operation, and hope to get your help. You can send your json file to : jwwang_2018@stu.xidian.edu.cn
Looking forward to your reply, thank you！

**Comment by wisaaco** [comment]
Hello, 
Sorry for the late, we had the files in an old backup. I upload the json files in the root of the master branch.
Best

**Comment by jiaweiwangwang** [comment]
I am very grateful for your help
